# Generated by Django 2.0.5 on 2018-05-29 13:10

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=100)),
                ('home_description', models.CharField(max_length=200)),
                ('home_price', models.IntegerField(default=0)),
                ('home_type', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Monolite'), (2, 'Brick'), (3, 'Clay')], max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Home'),
        ),
    ]
