# Generated by Django 2.0.5 on 2018-06-01 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_home_home_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
