# Generated by Django 2.0.5 on 2018-06-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_home_home_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_type',
            field=models.CharField(max_length=100),
        ),
    ]
